export const ChartOption = [
  {
    columnId: 'column-1',
    column: [
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '5',
        id: '1',
        dampak: '1',
        probabilitas: '5',
        label: '5',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-green-700 to-green-500',
        nilai: '4',
        id: '2',
        dampak: '1',
        probabilitas: '4',
        label: '4',
        legend: '2',
      },
      {
        color: 'bg-gradient-to-tr from-green-700 to-green-500',
        nilai: '3',
        id: '3',
        dampak: '1',
        probabilitas: '3',
        label: '3',
        legend: '2',
      },
      {
        color: 'bg-gradient-to-tr from-green-500 to-green-200',
        nilai: '2',
        id: '4',
        dampak: '1',
        probabilitas: '2',
        label: '2',
        legend: '1',
      },
      {
        color: 'bg-gradient-to-tr from-green-500 to-green-200',
        nilai: '1',
        id: '5',
        dampak: '1',
        probabilitas: '1',
        label: '1',
        legend: '1',
      },
    ],
    dampak: '1. Sangat rendah',
  },
  {
    columnId: 'column-2',
    column: [
      {
        color: 'bg-gradient-to-tr from-orange-600 to-orange-400',
        nilai: '10',
        id: '6',
        dampak: '2',
        probabilitas: '5',
        label: '10',
        legend: '4',
      },
      {
        color: 'bg-gradient-to-tr  from-yellow-500 to-yellow-200',
        nilai: '8',
        id: '7',
        dampak: '2',
        probabilitas: '4',
        label: '8',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '6',
        id: '8',
        dampak: '2',
        probabilitas: '3',
        label: '6',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-green-700 to-green-500',
        nilai: '4',
        id: '9',
        dampak: '2',
        probabilitas: '2',
        label: '4',
        legend: '2',
      },
      {
        color: 'bg-gradient-to-tr from-green-500 to-green-200',
        nilai: '2',
        id: '10',
        dampak: '2',
        probabilitas: '1',
        label: '2',
        legend: '1',
      },
    ],
    dampak: '2. Rendah',
  },
  {
    columnId: 'column-3',
    column: [
      {
        color: 'bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '15',
        id: '11',
        dampak: '3',
        probabilitas: '5',
        label: '15',
        legend: '5',
      },
      {
        color: 'bg-gradient-to-tr from-orange-600 to-orange-400',
        nilai: '12',
        id: '12',
        dampak: '3',
        probabilitas: '4',
        label: '12',
        legend: '4',
      },
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '9',
        id: '13',
        dampak: '3',
        probabilitas: '3',
        label: '9',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '6',
        id: '14',
        dampak: '3',
        probabilitas: '2',
        label: '6',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-green-700 to-green-500',
        nilai: '3',
        id: '15',
        dampak: '3',
        probabilitas: '1',
        label: '2',
        legend: '2',
      },
    ],
    dampak: '3. Sedang',
  },
  {
    columnId: 'column-4',
    column: [
      {
        color: 'bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '20',
        id: '16',
        dampak: '4',
        probabilitas: '5',
        label: '20',
        legend: '5',
      },
      {
        color: 'bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '16',
        id: '17',
        dampak: '4',
        probabilitas: '4',
        label: '16',
        legend: '5',
      },
      {
        color: 'bg-gradient-to-tr from-orange-600 to-orange-400',
        nilai: '12',
        id: '18',
        dampak: '4',
        probabilitas: '3',
        label: '12',
        legend: '4',
      },
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '8',
        id: '19',
        dampak: '4',
        probabilitas: '2',
        label: '8',
        legend: '3',
      },
      {
        color: 'bg-gradient-to-tr from-green-700 to-green-500',
        nilai: '4',
        id: '20',
        dampak: '1',
        probabilitas: '1',
        label: '4',
        legend: '2',
      },
    ],
    dampak: '4. Tinggi',
  },
  {
    columnId: 'column-5',
    column: [
      {
        color: ' bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '25',
        id: '21',
        dampak: '5',
        probabilitas: '5',
        label: '25',
        legend: '5',
      },
      {
        color: ' bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '20',
        id: '22',
        dampak: '5',
        probabilitas: '4',
        label: '20',
        legend: '5',
      },
      {
        color: ' bg-gradient-to-tr from-red-600 to-red-400',
        nilai: '15',
        id: '23',
        dampak: '5',
        probabilitas: '3',
        label: '15',
        legend: '5',
      },
      {
        color: 'bg-gradient-to-tr from-orange-600 to-orange-400',
        nilai: '10',
        id: '24',
        dampak: '5',
        probabilitas: '2',
        label: '10',
        legend: '4',
      },
      {
        color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
        nilai: '5',
        id: '25',
        dampak: '5',
        probabilitas: '1',
        label: '5',
        legend: '3',
      },
    ],
    dampak: '5. Sangat Tinggi',
  },
];

export const ChartLabelProbabilitas = [
  {
    label: '5. Almost Certain',
  },
  {
    label: '4. Likely',
  },
  {
    label: '3. Moderate',
  },
  {
    label: '2. Unlikely',
  },
  {
    label: '1. Rare',
  },
];

export const LegendLevelResiko = [
  {
    legendValue: '1',
    label: '1 - 2',
    text: 'Sangat Rendah',
    color: 'bg-gradient-to-tr from-green-500 to-green-200',
  },
  {
    legendValue: '2',
    label: '3 - 4',
    text: 'Rendah',
    color: 'bg-gradient-to-tr from-green-700 to-green-500',
  },
  {
    legendValue: '3',
    label: '5 - 9',
    text: 'Sedang',
    color: 'bg-gradient-to-tr from-yellow-500 to-yellow-200',
  },
  {
    legendValue: '4',
    label: '10 - 12',
    text: 'Tinggi',
    color: 'bg-gradient-to-tr from-orange-600 to-orange-400',
  },
  {
    legendValue: '5',
    label: '15 - 25',
    text: 'Sangat Tinggi',
    color: 'bg-gradient-to-tr from-red-600 to-red-400',
  },
];
